// apps/insighthunter-bookkeeping/src/components/auth/SignupForm.tsx
// src/components/auth/SignupForm.tsx
import { useState } from 'react';
import { FiMail, FiLock, FiUser, FiBriefcase } from 'react-icons/fi';
import './AuthForms.css';

export default function SignupForm() {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    companyName: '',
    password: '',
    confirmPassword: '',
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (formData.password !== formData.confirmPassword) {
      setError('Passwords do not match');
      return;
    }

    if (formData.password.length < 8) {
      setError('Password must be at least 8 characters');
      return;
    }

    setLoading(true);

    try {
      // Create user account (implement your auth logic)
      const response = await fetch('/api/auth/signup', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Failed to create account');
      }

      // Redirect to onboarding
      window.location.href = '/onboarding';
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to create account');
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="auth-form">
      {error && <div className="error-message">{error}</div>}

      <div className="form-group">
        <label>
          <FiUser /> Full Name
        </label>
        <input
          type="text"
          value={formData.name}
          onChange={(e) => setFormData({ ...formData, name: e.target.value })}
          placeholder="John Doe"
          required
        />
      </div>

      <div className="form-group">
        <label>
          <FiMail /> Email Address
        </label>
        <input
          type="email"
          value={formData.email}
          onChange={(e) => setFormData({ ...formData, email: e.target.value })}
          placeholder="john@company.com"
          required
        />
      </div>

      <div className="form-group">
        <label>
          <FiBriefcase /> Company Name
        </label>
        <input
          type="text"
          value={formData.companyName}
          onChange={(e) =>
            setFormData({ ...formData, companyName: e.target.value })
          }
          placeholder="Your Company Inc."
          required
        />
      </div>

      <div className="form-group">
        <label>
          <FiLock /> Password
        </label>
        <input
          type="password"
          value={formData.password}
          onChange={(e) => setFormData({ ...formData, password: e.target.value })}
          placeholder="Min. 8 characters"
          required
        />
      </div>

      <div className="form-group">
        <label>
          <FiLock /> Confirm Password
        </label>
        <input
          type="password"
          value={formData.confirmPassword}
          onChange={(e) =>
            setFormData({ ...formData, confirmPassword: e.target.value })
          }
          placeholder="Confirm your password"
          required
        />
      </div>

      <button type="submit" disabled={loading} className="submit-btn">
        {loading ? 'Creating account...' : 'Create Account'}
      </button>

      <p className="terms-text">
        By creating an account, you agree to our{' '}
        <a href="/terms">Terms of Service</a> and{' '}
        <a href="/privacy">Privacy Policy</a>
      </p>
    </form>
  );
}

// apps/insighthunter-main/src/components/islands/auth/SignupForm.svelte
<script lang="ts">
  let email = '';
  let password = '';
  let plan = 'lite';
  let loading = false;
  let error = '';
  let turnstileToken = '';

  async function handleSubmit(e: Event) {
    e.preventDefault();
    if (!turnstileToken) { error = 'Please complete the verification.'; return; }
    loading = true;
    error = '';

    try {
      const res = await fetch('/api/auth/signup', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password, plan, turnstileToken })
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.message || 'Signup failed');
      window.location.href = '/shop';
    } catch (err: any) {
      error = err.message;
    } finally {
      loading = false;
    }
  }

  // Turnstile callback (called by Cloudflare script)
  (window as any).onTurnstileSuccess = (token: string) => {
    turnstileToken = token;
  };
</script>

<div class="signup-wrapper">
  <h1>Create Your Account</h1>

  {#if error}
    <p class="error">{error}</p>
  {/if}

  <form on:submit={handleSubmit}>

    <div class="plan-selector">
      {#each ['lite', 'standard', 'pro'] as p}
        <button
          type="button"
          class="plan-btn"
          class:active={plan === p}
          on:click={() => plan = p}
        >
          {p.charAt(0).toUpperCase() + p.slice(1)}
        </button>
      {/each}
    </div>

    <label>
      Email
      <input type="email" bind:value={email} required />
    </label>

    <label>
      Password
      <input type="password" bind:value={password} required minlength="8" />
    </label>

    <!-- Cloudflare Turnstile -->
    <div
      class="cf-turnstile"
      data-sitekey="<your-turnstile-sitekey>"
      data-callback="onTurnstileSuccess"
    ></div>

    <button type="submit" disabled={loading || !turnstileToken} class="btn-primary">
      {loading ? 'Creating account...' : 'Create Account'}
    </button>

  </form>
</div>

<svelte:head>
  <script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>
</svelte:head>

<style>
  .signup-wrapper { max-width: 480px; margin: 4rem auto; padding: 2rem; }
  .plan-selector { display: flex; gap: 1rem; margin-bottom: 1.5rem; }
  .plan-btn { flex: 1; padding: 0.75rem; border: 1px solid var(--color-muted); background: transparent; color: var(--color-text); border-radius: 8px; cursor: pointer; }
  .plan-btn.active { border-color: var(--color-primary); color: var(--color-primary); }
  label { display: flex; flex-direction: column; gap: 0.25rem; margin-bottom: 1rem; }
  input { padding: 0.75rem; background: var(--color-surface); border: 1px solid var(--color-muted); border-radius: 8px; color: var(--color-text); }
  .error { color: #f87171; margin-bottom: 1rem; }
</style>
